"""Discover, allocate, and promote model versions inside ``TRAINING_ARTIFACTS_DIR``.

A "version" is a directory ``v<N>`` containing at minimum a trained
``marafone_model.joblib``. The pipeline always trains the next ``v<N+1>``
from data generated by the latest existing model.

Promotion = copying ``v<N>/marafone_model.joblib`` over
``artifacts/marafone_model.joblib`` (the file the Dockerfile bundles) and
writing the version name to ``artifacts/PRODUCTION``.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

from .config import (
    MODEL_FILENAME,
    PRODUCTION_MODEL_PATH,
    PRODUCTION_POINTER,
    PROMOTION_LOG,
    TRAINING_ARTIFACTS_DIR,
)

_VER_RE = re.compile(r"^v(\d+)$")


def recent_versions(limit: int | None = None) -> list[tuple[int, Path]]:
    """Return trained versions sorted from newest to oldest.

    The loose production model is exposed as version ``0`` when present so
    callers can build fallback pools even before the repository has ``v<N>``
    directories.
    """
    found: list[tuple[int, Path]] = []
    if TRAINING_ARTIFACTS_DIR.exists():
        for child in TRAINING_ARTIFACTS_DIR.iterdir():
            if not child.is_dir():
                continue
            m = _VER_RE.match(child.name)
            if not m:
                continue
            model_path = child / MODEL_FILENAME
            if model_path.exists():
                found.append((int(m.group(1)), model_path))
    found.sort(key=lambda item: item[0], reverse=True)
    if PRODUCTION_MODEL_PATH.exists() and not any(num == 0 for num, _ in found):
        found.append((0, PRODUCTION_MODEL_PATH))
    if limit is not None:
        return found[:limit]
    return found


def latest_version() -> tuple[int, Path | None]:
    """Return ``(num, model_path)`` for the latest trained ``v<N>`` directory.

    Fallback order:
      1. Highest ``v<N>`` directory containing ``marafone_model.joblib``.
      2. Loose ``artifacts/marafone_model.joblib`` (legacy / hand-placed) →
         returned as ``(0, …)`` so the next iteration becomes ``v1`` and
         trains on data generated from this baseline.
      3. Nothing → ``(0, None)``: bootstrap from random self-play.
    """
    found = recent_versions(limit=1)
    if found:
        return found[0]
    return 0, None


def next_version_dir() -> tuple[str, Path]:
    """Allocate the next ``v<N+1>`` directory and return ``(name, path)``."""
    n, _ = latest_version()
    name = f"v{n + 1}"
    path = TRAINING_ARTIFACTS_DIR / name
    path.mkdir(parents=True, exist_ok=True)
    return name, path


def production_version() -> str | None:
    """Read the currently-promoted version name (or ``None`` if unset)."""
    if not PRODUCTION_POINTER.exists():
        return None
    return PRODUCTION_POINTER.read_text(encoding="utf-8").strip() or None


def promoted_versions(limit: int | None = None) -> list[tuple[int, Path]]:
    """Return promoted versions sorted from newest to oldest.

    Reads from ``PROMOTION_LOG`` (one version name per line, oldest first).
    Falls back to the single entry in ``PRODUCTION_POINTER`` when the log
    doesn't exist yet — ensures backward compatibility with existing setups.
    """
    if not PROMOTION_LOG.exists():
        # Bootstrap: treat the current production version as the only entry.
        current = production_version()
        if current:
            m = _VER_RE.match(current)
            if m:
                p = TRAINING_ARTIFACTS_DIR / current / MODEL_FILENAME
                if p.exists():
                    return [(int(m.group(1)), p)]
        return []

    entries: list[tuple[int, Path]] = []
    for line in PROMOTION_LOG.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        m = _VER_RE.match(line)
        if not m:
            continue
        p = TRAINING_ARTIFACTS_DIR / line / MODEL_FILENAME
        if p.exists():
            entries.append((int(m.group(1)), p))
    # Deduplicate (keep latest occurrence) and sort newest→oldest.
    seen: dict[int, Path] = {}
    for num, path in entries:
        seen[num] = path
    result = sorted(seen.items(), key=lambda x: x[0], reverse=True)
    return result[:limit] if limit is not None else result


def promote(version_name: str, version_dir: Path) -> None:
    """Copy ``v<N>``'s model into the production slot and update the pointer."""
    src = version_dir / MODEL_FILENAME
    if not src.exists():
        raise FileNotFoundError(f"Cannot promote — model not found: {src}")
    PRODUCTION_MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, PRODUCTION_MODEL_PATH)
    PRODUCTION_POINTER.write_text(version_name + "\n", encoding="utf-8")
    # Append to the promotion log so promoted_versions() can reconstruct history.
    PROMOTION_LOG.parent.mkdir(parents=True, exist_ok=True)
    with PROMOTION_LOG.open("a", encoding="utf-8") as f:
        f.write(version_name + "\n")
