"""Discover, allocate, and promote model versions inside ``TRAINING_ARTIFACTS_DIR``.

A "version" is a directory ``v<N>`` containing at minimum a trained
``marafone_model.joblib``. The pipeline always trains the next ``v<N+1>``
from data generated by the latest existing model.

Promotion = copying ``v<N>/marafone_model.joblib`` over
``artifacts/marafone_model.joblib`` (the file the Dockerfile bundles) and
writing the version name to ``artifacts/PRODUCTION``.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

from .config import (
    MODEL_FILENAME,
    PRODUCTION_MODEL_PATH,
    PRODUCTION_POINTER,
    TRAINING_ARTIFACTS_DIR,
)

_VER_RE = re.compile(r"^v(\d+)$")


def latest_version() -> tuple[int, Path | None]:
    """Return ``(num, model_path)`` for the latest trained ``v<N>`` directory.

    Fallback order:
      1. Highest ``v<N>`` directory containing ``marafone_model.joblib``.
      2. Loose ``artifacts/marafone_model.joblib`` (legacy / hand-placed) →
         returned as ``(0, …)`` so the next iteration becomes ``v1`` and
         trains on data generated from this baseline.
      3. Nothing → ``(0, None)``: bootstrap from random self-play.
    """
    best_num = 0
    best_path: Path | None = None
    if TRAINING_ARTIFACTS_DIR.exists():
        for child in TRAINING_ARTIFACTS_DIR.iterdir():
            if not child.is_dir():
                continue
            m = _VER_RE.match(child.name)
            if not m:
                continue
            n = int(m.group(1))
            if n > best_num and (child / MODEL_FILENAME).exists():
                best_num = n
                best_path = child / MODEL_FILENAME
    if best_path is not None:
        return best_num, best_path
    if PRODUCTION_MODEL_PATH.exists():
        return 0, PRODUCTION_MODEL_PATH
    return 0, None


def next_version_dir() -> tuple[str, Path]:
    """Allocate the next ``v<N+1>`` directory and return ``(name, path)``."""
    n, _ = latest_version()
    name = f"v{n + 1}"
    path = TRAINING_ARTIFACTS_DIR / name
    path.mkdir(parents=True, exist_ok=True)
    return name, path


def production_version() -> str | None:
    """Read the currently-promoted version name (or ``None`` if unset)."""
    if not PRODUCTION_POINTER.exists():
        return None
    return PRODUCTION_POINTER.read_text(encoding="utf-8").strip() or None


def promote(version_name: str, version_dir: Path) -> None:
    """Copy ``v<N>``'s model into the production slot and update the pointer."""
    src = version_dir / MODEL_FILENAME
    if not src.exists():
        raise FileNotFoundError(f"Cannot promote — model not found: {src}")
    PRODUCTION_MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, PRODUCTION_MODEL_PATH)
    PRODUCTION_POINTER.write_text(version_name + "\n", encoding="utf-8")
