[tool.poetry]
name = "aimarafone"
version = "0.1.0"
description = "For-fun teaching an AI agent with RL to play Marafone (card game from Romagna)"
authors = ["Federico <federico.fabiani96@gmail.com>"]
license = "BSD 3-Clause License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0.2"
pydantic = "^2.10.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
